services:
  client:
    container_name: hobbit_dev_client
    build: ./client
    image: hobbit_client
    ports: 
      - 8080:8080
    working_dir: /code
    volumes:
      - type: bind
        source: ./client
        target: /code
    command: [ "http-server" ]
  api:
    container_name: hobbit_dev_api
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=hobbit
      - PGHOST=db
      - PGPASSWORD=password
      - PGDATABASE=tracker
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    container_name: hobbit_dev_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=tracker
      - POSTGRES_USER=hobbit
      - POSTGRES_PASSWORD=password
volumes:
  dbdata: